[transforms]
s2_transforms = ['resize']
s2_band_size = [224, 224]

[data_loader]
qualities = [2, 3]
s2_avg_by = 4
batch_size = 32
shuffle = false
num_workers = 0
interpolate = false
filter_clouds = true
filter_by_QA60 = true
filter_by_threshold = 0.31
log_yields = false

indexes = []
s2_bands = ['S2_B2', 'S2_B3', 'S2_B4', 'S2_B5', 'S2_B8']
clim_bands = []	
soil = []	
        
[augmentations]
p_aug = 0.5
p_flip = 0.2
p_crop = 0.1
p_rotate = 0.1
p_cutout = 0.1
p_mixup = 0.5

  [augmentations.rotate]
  pad = 5
  degrees = 10

  [augmentations.crop]
  pad = 25

  [augmentations.cutout]
  n_cuts_max = 3
  cut_size = 25

  [augmentations.mixup]
  alpha = 0.4