[CropNet]
n_head = 512
dropout = 0.25

  [CropNet.s2_cnn]
  bn_first = false
  attention = false
  n_out = 256

  [CropNet.s2_seq]
  hidden_size = 512
  n_layers = 1
  dropout = 0
  bi = false
  n_head = 256

  [CropNet.clim_seq]
  hidden_size = 512
  n_layers = 1
  dropout = 0
  bi = false
  n_head = 256

[train_params]
lr = 1e-3
n_iters= 2000
n_iters_eval = 500
plot_mode = true
val_size = 0.2
save_best_val = false
checkpoint_path = './models_weights'