[CropNet]
n_head = 512
dropout = 0.2

  [CropNet.s2_cnn]
  bn_first = false

  [CropNet.s2_lstm]
  hidden_size = 512
  n_layers = 1
  dropout = 0
  bi = false
  n_head = 256

  [CropNet.clim_sltm]
  hidden_size = 512
  n_layers = 1
  dropout = 0
  bi = false
  n_head = 256

[train_params]
lr = 3e-4
n_epochs = 200
plot_mode = true
val_size = 0.2
save_best_val = false
checkpoint_path = './models_weights'