[CropNet]
n_head = 256
p_drp = 0.3
add_year = false

  [CropNet.s2_cnn]
  attention = true

  [CropNet.s2_seq]
  hidden_size = 512
  n_layers = 1
  dropout = 0
  bi = false
  n_head = 256
  p_drp = 0.2

  [CropNet.soil]
  n_head = 128

  [CropNet.clim_seq]
  hidden_size = 512
  n_layers = 1
  dropout = 0
  bi = false
  n_head = 256
  p_drp = 0.2

[train_params]
lr = 1e-3
n_iters= 500
n_iters_eval = 30
plot_mode = true
save_best_val = false
checkpoint_path = './models_weights'