[ClimNet]
input_dim = 13
hidden_dim = 512
head_dim = 256
lstm_num_layers = 1
lstm_dropout = 0
head_dropout = 0
bi = false
month_to_proc = 11

[S2ClimNet]
n_head = 256
p_dropout = 0

[s2_model_params]
backbone = 'resnet18'
n_head = 256
p_dropout = 0.2

[train_params]
lr = 0.1e-3
n_epochs = 200
plot_mode = true
val_size = 0.2
save_best_val = false
checkpoint_path = '/gdrive/My Drive/Colab Notebooks/Competitions/CGIAR Crop Yield Prediction Challenge/models_weights'